### ISSUE TITLE
tripwire 2.4.3.2 on alpine won't compile

### ISSUE THREAD

**Issue by mk-f** [Tripwire/tripwire-open-source#15]
Tripwire 2.4.3.2 won't compile on Alpine Linux 3.5, Tripwire 2.4.3.1 works fine.
[config.log.txt](https://github.com/Tripwire/tripwire-open-source/files/787730/config.log.txt)

```make
make[3]: Leaving directory '/home/vagrant/src/tripwire/tripwire-open-source-2.4.3.2/src/cryptlib'
Making all in core
make[3]: Entering directory '/home/vagrant/src/tripwire/tripwire-open-source-2.4.3.2/src/core'
g++ -DHAVE_CONFIG_H		 -I. -I../..  -I./..   -O -pipe -Wall -Wextra -Wno-unused-parameter -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -c -o archive.o archive.cpp
In file included from archive.cpp:42:0:
fsservices.h:294:36: error: 'uid_t' has not been declared
   virtual bool        GetUserName( uid_t user_id, TSTRING& tstrUser ) const = 0;
                                    ^~~~~
fsservices.h:295:37: error: 'gid_t' has not been declared
   virtual bool        GetGroupName( gid_t group_id, TSTRING& tstrGroup ) const = 0;
                                     ^~~~~
make[3]: *** [Makefile:411: archive.o] Error 1
make[3]: Leaving directory '/home/vagrant/src/tripwire/tripwire-open-source-2.4.3.2/src/core'
make[2]: *** [Makefile:340: all-recursive] Error 1
make[2]: Leaving directory '/home/vagrant/src/tripwire/tripwire-open-source-2.4.3.2/src'
make[1]: *** [Makefile:385: all-recursive] Error 1
make[1]: Leaving directory '/home/vagrant/src/tripwire/tripwire-open-source-2.4.3.2'
make: *** [Makefile:326: all] Error 2
```
adding ``#include <sys/stat.h>`` to ``src/core/fsservices.h`` fixes the build, but will fail on ``make install``:
```
make[3]: Entering directory '/home/vagrant/src/tripwire/tripwire-open-source-2.4.3.2/src/cryptlib'
make[3]: Nothing to be done for 'install-exec-am'.
 ../.././install-sh -c -d '.'
 /usr/bin/install -c -m 644 algebra.h asn.h config.h cryptlib.h des.h elgamal.h eprecomp.h filters.h forkjoin.h integer.h iterhash.h misc.h modarith.h nbtheory.h pch.h queue.h rng.h sha.h smartptr.h words.h zbits.h zdeflate.h zinflate.h ztrees.h '.'
install: 'algebra.h' and './algebra.h' are the same file
install: 'asn.h' and './asn.h' are the same file
install: 'config.h' and './config.h' are the same file
install: 'cryptlib.h' and './cryptlib.h' are the same file
install: 'des.h' and './des.h' are the same file
install: 'elgamal.h' and './elgamal.h' are the same file
install: 'eprecomp.h' and './eprecomp.h' are the same file
install: 'filters.h' and './filters.h' are the same file
install: 'forkjoin.h' and './forkjoin.h' are the same file
install: 'integer.h' and './integer.h' are the same file
install: 'iterhash.h' and './iterhash.h' are the same file
install: 'misc.h' and './misc.h' are the same file
install: 'modarith.h' and './modarith.h' are the same file
install: 'nbtheory.h' and './nbtheory.h' are the same file
install: 'pch.h' and './pch.h' are the same file
install: 'queue.h' and './queue.h' are the same file
install: 'rng.h' and './rng.h' are the same file
install: 'sha.h' and './sha.h' are the same file
install: 'smartptr.h' and './smartptr.h' are the same file
install: 'words.h' and './words.h' are the same file
install: 'zbits.h' and './zbits.h' are the same file
install: 'zdeflate.h' and './zdeflate.h' are the same file
install: 'zinflate.h' and './zinflate.h' are the same file
install: 'ztrees.h' and './ztrees.h' are the same file
make[3]: *** [Makefile:392: install-libcryptlib_aHEADERS] Error 1
make[3]: Leaving directory '/home/vagrant/src/tripwire/tripwire-open-source-2.4.3.2/src/cryptlib'
make[2]: *** [Makefile:507: install-am] Error 2
make[2]: Leaving directory '/home/vagrant/src/tripwire/tripwire-open-source-2.4.3.2/src/cryptlib'
make[1]: *** [Makefile:340: install-recursive] Error 1
make[1]: Leaving directory '/home/vagrant/src/tripwire/tripwire-open-source-2.4.3.2/src'
make: *** [Makefile:385: install-recursive] Error 1
```

**Comment by brc0x1** [comment]
Thanks for reporting this, I've fixed the include problem on the new dev/2.4.3.3 branch.  Was able to repro with an Alpine 3.3.3 vm.  Still working the "make install" part of the issue right now.

**Comment by brc0x1** [comment]
@mk-f Ok, I think I've sorted out the install problem too, if you're interested in trying out the dev/2.4.3.3 branch.

**Comment by mk-f** [comment]
@brc0x1 Thanks for the fast replies and fix, i tested on a clean alpine 3.5 and the dev/2.4.3.3 branch works as expected.

**Comment by mk-f** [comment]
Retested with 2.4.3.3-release, all fine, thank you.
